/**
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export enum OperatorType {
    EQUALS = 'EQUALS',
    NOT_EQUALS = 'NOT_EQUALS',
    LOWER = 'LOWER',
    LOWER_OR_EQUALS = 'LOWER_OR_EQUALS',
    GREATER = 'GREATER',
    GREATER_OR_EQUALS = 'GREATER_OR_EQUALS',
    BETWEEN = 'BETWEEN',
    IN = 'IN',
    IS = 'IS',
    CONTAINS = 'CONTAINS',
    BEGINS_WITH = 'BEGINS_WITH',
    ENDS_WITH = 'ENDS_WITH',
    EXISTS = 'EXISTS',
    NOT_EXISTS = 'NOT_EXISTS',
    IS_PART_OF = 'IS_PART_OF',
    IS_NOT_PART_OF = 'IS_NOT_PART_OF',
}

export enum CombinatorType {
    AND = 'AND',
    OR = 'OR',
}

export enum FieldType {
    ID = 'ID',
    NAME = 'NAME',
    NOMINAL_VOLTAGE = 'NOMINAL_VOLTAGE',
    MIN_P = 'MIN_P',
    MAX_P = 'MAX_P',
    TARGET_V = 'TARGET_V',
    TARGET_P = 'TARGET_P',
    TARGET_Q = 'TARGET_Q',
    ENERGY_SOURCE = 'ENERGY_SOURCE',
    COUNTRY = 'COUNTRY',
    VOLTAGE_REGULATOR_ON = 'VOLTAGE_REGULATOR_ON',
    PLANNED_ACTIVE_POWER_SET_POINT = 'PLANNED_ACTIVE_POWER_SET_POINT',
    RATED_S = 'RATED_S',
    MARGINAL_COST = 'MARGINAL_COST',
    PLANNED_OUTAGE_RATE = 'PLANNED_OUTAGE_RATE',
    FORCED_OUTAGE_RATE = 'FORCED_OUTAGE_RATE',
    VOLTAGE_LEVEL_ID = 'VOLTAGE_LEVEL_ID',
    P0 = 'P0',
    Q0 = 'Q0',
    LOW_VOLTAGE_LIMIT = 'LOW_VOLTAGE_LIMIT',
    HIGH_VOLTAGE_LIMIT = 'HIGH_VOLTAGE_LIMIT',
    SECTION_COUNT = 'SECTION_COUNT',
    MAXIMUM_SECTION_COUNT = 'MAXIMUM_SECTION_COUNT',
    SHUNT_COMPENSATOR_TYPE = 'SHUNT_COMPENSATOR_TYPE',
    CONNECTED = 'CONNECTED',
    MAX_Q_AT_NOMINAL_V = 'MAX_Q_AT_NOMINAL_V',
    SWITCHED_ON_Q_AT_NOMINAL_V = 'SWITCHED_ON_Q_AT_NOMINAL_V',
    MAX_SUSCEPTANCE = 'MAX_SUSCEPTANCE',
    SWITCHED_ON_SUSCEPTANCE = 'SWITCHED_ON_SUSCEPTANCE',
    CONNECTED_1 = 'CONNECTED_1',
    CONNECTED_2 = 'CONNECTED_2',
    VOLTAGE_LEVEL_ID_1 = 'VOLTAGE_LEVEL_ID_1',
    VOLTAGE_LEVEL_ID_2 = 'VOLTAGE_LEVEL_ID_2',
    NOMINAL_VOLTAGE_1 = 'NOMINAL_VOLTAGE_1',
    NOMINAL_VOLTAGE_2 = 'NOMINAL_VOLTAGE_2',
    COUNTRY_1 = 'COUNTRY_1',
    COUNTRY_2 = 'COUNTRY_2',
    SERIE_RESISTANCE = 'SERIE_RESISTANCE',
    SERIE_REACTANCE = 'SERIE_REACTANCE',
    SHUNT_CONDUCTANCE_1 = 'SHUNT_CONDUCTANCE_1',
    SHUNT_CONDUCTANCE_2 = 'SHUNT_CONDUCTANCE_2',
    SHUNT_SUSCEPTANCE_1 = 'SHUNT_SUSCEPTANCE_1',
    SHUNT_SUSCEPTANCE_2 = 'SHUNT_SUSCEPTANCE_2',
    MAGNETIZING_CONDUCTANCE = 'MAGNETIZING_CONDUCTANCE',
    MAGNETIZING_SUSCEPTANCE = 'MAGNETIZING_SUSCEPTANCE',
    LOAD_TYPE = 'LOAD_TYPE',
    RATED_VOLTAGE_1 = 'RATED_VOLTAGE_1',
    RATED_VOLTAGE_2 = 'RATED_VOLTAGE_2',
    HAS_RATIO_TAP_CHANGER = 'HAS_RATIO_TAP_CHANGER',
    RATIO_REGULATING = 'RATIO_REGULATING',
    LOAD_TAP_CHANGING_CAPABILITIES = 'LOAD_TAP_CHANGING_CAPABILITIES',
    RATIO_REGULATION_MODE = 'RATIO_REGULATION_MODE',
    RATIO_TARGET_V = 'RATIO_TARGET_V',
    HAS_PHASE_TAP_CHANGER = 'HAS_PHASE_TAP_CHANGER',
    PHASE_REGULATING = 'PHASE_REGULATING',
    PHASE_REGULATION_MODE = 'PHASE_REGULATION_MODE',
    PHASE_REGULATION_VALUE = 'PHASE_REGULATION_VALUE',
    PROPERTY = 'FREE_PROPERTIES',
    SUBSTATION_PROPERTY = 'SUBSTATION_PROPERTIES',
    SUBSTATION_PROPERTY_1 = 'SUBSTATION_PROPERTIES_1',
    SUBSTATION_PROPERTY_2 = 'SUBSTATION_PROPERTIES_2',
}

export enum DataType {
    STRING = 'STRING',
    ENUM = 'ENUM',
    NUMBER = 'NUMBER',
    BOOLEAN = 'BOOLEAN',
    COMBINATOR = 'COMBINATOR',
    FILTER_UUID = 'FILTER_UUID',
    PROPERTY = 'PROPERTIES',
}

export interface RuleTypeExport {
    field: FieldType;
    operator: OperatorType;
    value: string | number | undefined;
    values: string[] | number[] | undefined;
    dataType: DataType;
    propertyName?: string;
    propertyValues?: string[];
}

export interface RuleGroupTypeExport {
    combinator: CombinatorType;
    dataType: DataType;
    rules: (RuleTypeExport | RuleGroupTypeExport)[];
}
